### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by Yogeshkad** [CodeMazeBlog/identity-aspnetcore#2]
If i run the application which in this repository.

I created one user in the application

i login in application all works

i open  different browser and open application url

and then in that browser if i copy past the old browser cookies 
after that refresh  boom ! boom ! user getting access to application without login by just copying the cookies of other user

**Comment by CodeMazeBlog** [comment]
It's indeed a security issue, so be aware of who do you give your computer access to.
